sonar.projectKey=VidiomTM_sitcom-pilot
sonar.organization=vidiomtm
sonar.host.url=https://sonarcloud.io

sonar.sources=src/showrunner
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.12
sonar.exclusions=legacy/**,aiservices/**
sonar.coverage.exclusions=tests/**,legacy/**,aiservices/**

sonar.python.ruff.reportPaths=ruff-report.json
